.IX Title "CPU-G 1"
.TH CPU-G 1 "2009-10-11" CPU-G CPU-G

.SH "NAME"
CPU\-G \- A program that shows useful information about your hardware.

.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\fBCPU\-G\fP is a program that shows useful information about your hardware. It collects and displays information about your CPU, RAM, Motherboard, some general information about your system and more.

.SH "AUTHOR"
.IX Header "AUTHOR"
Fotis Tsamis <ftsamis@gmail.com>

.SH "LICENSE"
.IX Header "LICENSE"
This manpage and the \fBCPU-G\fP utility  was  written  by Fotis Tsamis <ftsamis@gmail.com> for GNU/Linux systems.  Permission is granted to copy, distribute and/or modify  this  document  under the terms of the GNU General Public License, Version 3 or any later version published by the Free  Software  Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL-3.
